/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_explorer_address_status.h
 *
 * 
 */

#ifndef OAI_api_v1_explorer_address_status_H
#define OAI_api_v1_explorer_address_status_H

#include <QJsonObject>



#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_explorer_address_status: public OAIObject {
public:
    OAI_api_v1_explorer_address_status();
    OAI_api_v1_explorer_address_status(QString json);
    ~OAI_api_v1_explorer_address_status() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isUnconfirmed() const;
    void setUnconfirmed(const bool &unconfirmed);

    qint64 getBlockSeq() const;
    void setBlockSeq(const qint64 &block_seq);

    qint64 getLabel() const;
    void setLabel(const qint64 &label);

    bool isConfirmed() const;
    void setConfirmed(const bool &confirmed);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    bool unconfirmed;
    bool m_unconfirmed_isSet;
    bool m_unconfirmed_isValid;
    qint64 block_seq;
    bool m_block_seq_isSet;
    bool m_block_seq_isValid;
    qint64 label;
    bool m_label_isSet;
    bool m_label_isValid;
    bool confirmed;
    bool m_confirmed_isSet;
    bool m_confirmed_isValid;
};

}

#endif // OAI_api_v1_explorer_address_status_H
