/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_wallets_entries.h
 *
 * 
 */

#ifndef OAI_api_v1_wallets_entries_H
#define OAI_api_v1_wallets_entries_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_wallets_entries: public OAIObject {
public:
    OAI_api_v1_wallets_entries();
    OAI_api_v1_wallets_entries(QString json);
    ~OAI_api_v1_wallets_entries() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPublicKey() const;
    void setPublicKey(const QString &public_key);

    QString getAddress() const;
    void setAddress(const QString &address);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString public_key;
    bool m_public_key_isSet;
    bool m_public_key_isValid;
    QString address;
    bool m_address_isSet;
    bool m_address_isValid;
};

}

#endif // OAI_api_v1_wallets_entries_H
