/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAI_api_v1_pendingTxs_transaction.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAI_api_v1_pendingTxs_transaction::OAI_api_v1_pendingTxs_transaction(QString json) {
    this->init();
    this->fromJson(json);
}

OAI_api_v1_pendingTxs_transaction::OAI_api_v1_pendingTxs_transaction() {
    this->init();
}

OAI_api_v1_pendingTxs_transaction::~OAI_api_v1_pendingTxs_transaction() {

}

void
OAI_api_v1_pendingTxs_transaction::init() {
    m_outputs_isSet = false;
    m_outputs_isValid = false;
    m_inner_hash_isSet = false;
    m_inner_hash_isValid = false;
    m_inputs_isSet = false;
    m_inputs_isValid = false;
    m_sigs_isSet = false;
    m_sigs_isValid = false;
    m_length_isSet = false;
    m_length_isValid = false;
    m_txid_isSet = false;
    m_txid_isValid = false;
    m_type_isSet = false;
    m_type_isValid = false;
    m_timestamp_isSet = false;
    m_timestamp_isValid = false;
}

void
OAI_api_v1_pendingTxs_transaction::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAI_api_v1_pendingTxs_transaction::fromJsonObject(QJsonObject json) {
    
    m_outputs_isValid = ::skyqt::fromJsonValue(outputs, json[QString("outputs")]);
    m_inner_hash_isValid = ::skyqt::fromJsonValue(inner_hash, json[QString("inner_hash")]);
    
    
    m_inputs_isValid = ::skyqt::fromJsonValue(inputs, json[QString("inputs")]);
    
    m_sigs_isValid = ::skyqt::fromJsonValue(sigs, json[QString("sigs")]);
    m_length_isValid = ::skyqt::fromJsonValue(length, json[QString("length")]);
    
    m_txid_isValid = ::skyqt::fromJsonValue(txid, json[QString("txid")]);
    
    m_type_isValid = ::skyqt::fromJsonValue(type, json[QString("type")]);
    
    m_timestamp_isValid = ::skyqt::fromJsonValue(timestamp, json[QString("timestamp")]);
    
}

QString
OAI_api_v1_pendingTxs_transaction::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAI_api_v1_pendingTxs_transaction::asJsonObject() const {
    QJsonObject obj;
	
    if(outputs.size() > 0){
        obj.insert(QString("outputs"), ::skyqt::toJsonValue(outputs));
    } 
	if(m_inner_hash_isSet){
        obj.insert(QString("inner_hash"), ::skyqt::toJsonValue(inner_hash));
    }
	
    if(inputs.size() > 0){
        obj.insert(QString("inputs"), ::skyqt::toJsonValue(inputs));
    } 
	
    if(sigs.size() > 0){
        obj.insert(QString("sigs"), ::skyqt::toJsonValue(sigs));
    } 
	if(m_length_isSet){
        obj.insert(QString("length"), ::skyqt::toJsonValue(length));
    }
	if(m_txid_isSet){
        obj.insert(QString("txid"), ::skyqt::toJsonValue(txid));
    }
	if(m_type_isSet){
        obj.insert(QString("type"), ::skyqt::toJsonValue(type));
    }
	if(m_timestamp_isSet){
        obj.insert(QString("timestamp"), ::skyqt::toJsonValue(timestamp));
    }
    return obj;
}

QList<OAI_api_v1_explorer_address_outputs>
OAI_api_v1_pendingTxs_transaction::getOutputs() const {
    return outputs;
}
void
OAI_api_v1_pendingTxs_transaction::setOutputs(const QList<OAI_api_v1_explorer_address_outputs> &outputs) {
    this->outputs = outputs;
    this->m_outputs_isSet = true;
}

QString
OAI_api_v1_pendingTxs_transaction::getInnerHash() const {
    return inner_hash;
}
void
OAI_api_v1_pendingTxs_transaction::setInnerHash(const QString &inner_hash) {
    this->inner_hash = inner_hash;
    this->m_inner_hash_isSet = true;
}

QList<QString>
OAI_api_v1_pendingTxs_transaction::getInputs() const {
    return inputs;
}
void
OAI_api_v1_pendingTxs_transaction::setInputs(const QList<QString> &inputs) {
    this->inputs = inputs;
    this->m_inputs_isSet = true;
}

QList<QString>
OAI_api_v1_pendingTxs_transaction::getSigs() const {
    return sigs;
}
void
OAI_api_v1_pendingTxs_transaction::setSigs(const QList<QString> &sigs) {
    this->sigs = sigs;
    this->m_sigs_isSet = true;
}

qint32
OAI_api_v1_pendingTxs_transaction::getLength() const {
    return length;
}
void
OAI_api_v1_pendingTxs_transaction::setLength(const qint32 &length) {
    this->length = length;
    this->m_length_isSet = true;
}

QString
OAI_api_v1_pendingTxs_transaction::getTxid() const {
    return txid;
}
void
OAI_api_v1_pendingTxs_transaction::setTxid(const QString &txid) {
    this->txid = txid;
    this->m_txid_isSet = true;
}

qint32
OAI_api_v1_pendingTxs_transaction::getType() const {
    return type;
}
void
OAI_api_v1_pendingTxs_transaction::setType(const qint32 &type) {
    this->type = type;
    this->m_type_isSet = true;
}

qint32
OAI_api_v1_pendingTxs_transaction::getTimestamp() const {
    return timestamp;
}
void
OAI_api_v1_pendingTxs_transaction::setTimestamp(const qint32 &timestamp) {
    this->timestamp = timestamp;
    this->m_timestamp_isSet = true;
}

bool
OAI_api_v1_pendingTxs_transaction::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(outputs.size() > 0){ isObjectUpdated = true; break;}
    
        if(m_inner_hash_isSet){ isObjectUpdated = true; break;}
    
        if(inputs.size() > 0){ isObjectUpdated = true; break;}
    
        if(sigs.size() > 0){ isObjectUpdated = true; break;}
    
        if(m_length_isSet){ isObjectUpdated = true; break;}
    
        if(m_txid_isSet){ isObjectUpdated = true; break;}
    
        if(m_type_isSet){ isObjectUpdated = true; break;}
    
        if(m_timestamp_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAI_api_v1_pendingTxs_transaction::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

