/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAI_api_v1_explorer_address_outputs.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAI_api_v1_explorer_address_outputs::OAI_api_v1_explorer_address_outputs(QString json) {
    this->init();
    this->fromJson(json);
}

OAI_api_v1_explorer_address_outputs::OAI_api_v1_explorer_address_outputs() {
    this->init();
}

OAI_api_v1_explorer_address_outputs::~OAI_api_v1_explorer_address_outputs() {

}

void
OAI_api_v1_explorer_address_outputs::init() {
    m_hours_isSet = false;
    m_hours_isValid = false;
    m_dst_isSet = false;
    m_dst_isValid = false;
    m_coins_isSet = false;
    m_coins_isValid = false;
    m_uxid_isSet = false;
    m_uxid_isValid = false;
}

void
OAI_api_v1_explorer_address_outputs::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAI_api_v1_explorer_address_outputs::fromJsonObject(QJsonObject json) {
    m_hours_isValid = ::skyqt::fromJsonValue(hours, json[QString("hours")]);
    
    m_dst_isValid = ::skyqt::fromJsonValue(dst, json[QString("dst")]);
    
    m_coins_isValid = ::skyqt::fromJsonValue(coins, json[QString("coins")]);
    
    m_uxid_isValid = ::skyqt::fromJsonValue(uxid, json[QString("uxid")]);
    
}

QString
OAI_api_v1_explorer_address_outputs::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAI_api_v1_explorer_address_outputs::asJsonObject() const {
    QJsonObject obj;
	if(m_hours_isSet){
        obj.insert(QString("hours"), ::skyqt::toJsonValue(hours));
    }
	if(m_dst_isSet){
        obj.insert(QString("dst"), ::skyqt::toJsonValue(dst));
    }
	if(m_coins_isSet){
        obj.insert(QString("coins"), ::skyqt::toJsonValue(coins));
    }
	if(m_uxid_isSet){
        obj.insert(QString("uxid"), ::skyqt::toJsonValue(uxid));
    }
    return obj;
}

qint64
OAI_api_v1_explorer_address_outputs::getHours() const {
    return hours;
}
void
OAI_api_v1_explorer_address_outputs::setHours(const qint64 &hours) {
    this->hours = hours;
    this->m_hours_isSet = true;
}

QString
OAI_api_v1_explorer_address_outputs::getDst() const {
    return dst;
}
void
OAI_api_v1_explorer_address_outputs::setDst(const QString &dst) {
    this->dst = dst;
    this->m_dst_isSet = true;
}

QString
OAI_api_v1_explorer_address_outputs::getCoins() const {
    return coins;
}
void
OAI_api_v1_explorer_address_outputs::setCoins(const QString &coins) {
    this->coins = coins;
    this->m_coins_isSet = true;
}

QString
OAI_api_v1_explorer_address_outputs::getUxid() const {
    return uxid;
}
void
OAI_api_v1_explorer_address_outputs::setUxid(const QString &uxid) {
    this->uxid = uxid;
    this->m_uxid_isSet = true;
}

bool
OAI_api_v1_explorer_address_outputs::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_hours_isSet){ isObjectUpdated = true; break;}
    
        if(m_dst_isSet){ isObjectUpdated = true; break;}
    
        if(m_coins_isSet){ isObjectUpdated = true; break;}
    
        if(m_uxid_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAI_api_v1_explorer_address_outputs::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

