/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_explorer_address_inputs.h
 *
 * 
 */

#ifndef OAI_api_v1_explorer_address_inputs_H
#define OAI_api_v1_explorer_address_inputs_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_explorer_address_inputs: public OAIObject {
public:
    OAI_api_v1_explorer_address_inputs();
    OAI_api_v1_explorer_address_inputs(QString json);
    ~OAI_api_v1_explorer_address_inputs() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getOwner() const;
    void setOwner(const QString &owner);

    qint64 getHours() const;
    void setHours(const qint64 &hours);

    qint64 getCalculatedHours() const;
    void setCalculatedHours(const qint64 &calculated_hours);

    QString getCoins() const;
    void setCoins(const QString &coins);

    QString getUxid() const;
    void setUxid(const QString &uxid);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString owner;
    bool m_owner_isSet;
    bool m_owner_isValid;
    qint64 hours;
    bool m_hours_isSet;
    bool m_hours_isValid;
    qint64 calculated_hours;
    bool m_calculated_hours_isSet;
    bool m_calculated_hours_isValid;
    QString coins;
    bool m_coins_isSet;
    bool m_coins_isValid;
    QString uxid;
    bool m_uxid_isSet;
    bool m_uxid_isValid;
};

}

#endif // OAI_api_v1_explorer_address_inputs_H
