/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_wallet_transaction_wallet.h
 *
 * 
 */

#ifndef OAI_api_v1_wallet_transaction_wallet_H
#define OAI_api_v1_wallet_transaction_wallet_H

#include <QJsonObject>


#include <QList>
#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_wallet_transaction_wallet: public OAIObject {
public:
    OAI_api_v1_wallet_transaction_wallet();
    OAI_api_v1_wallet_transaction_wallet(QString json);
    ~OAI_api_v1_wallet_transaction_wallet() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getUnspents() const;
    void setUnspents(const QList<QString> &unspents);

    QList<QString> getAddresses() const;
    void setAddresses(const QList<QString> &addresses);

    QString getPassword() const;
    void setPassword(const QString &password);

    QString getId() const;
    void setId(const QString &id);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QList<QString> unspents;
    bool m_unspents_isSet;
    bool m_unspents_isValid;
    QList<QString> addresses;
    bool m_addresses_isSet;
    bool m_addresses_isValid;
    QString password;
    bool m_password_isSet;
    bool m_password_isValid;
    QString id;
    bool m_id_isSet;
    bool m_id_isValid;
};

}

#endif // OAI_api_v1_wallet_transaction_wallet_H
