/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_pendingTxs_transaction.h
 *
 * BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 */

#ifndef OAI_api_v1_pendingTxs_transaction_H
#define OAI_api_v1_pendingTxs_transaction_H

#include <QJsonObject>


#include "OAI_api_v1_explorer_address_outputs.h"
#include <QList>
#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_pendingTxs_transaction: public OAIObject {
public:
    OAI_api_v1_pendingTxs_transaction();
    OAI_api_v1_pendingTxs_transaction(QString json);
    ~OAI_api_v1_pendingTxs_transaction() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAI_api_v1_explorer_address_outputs> getOutputs() const;
    void setOutputs(const QList<OAI_api_v1_explorer_address_outputs> &outputs);

    QString getInnerHash() const;
    void setInnerHash(const QString &inner_hash);

    QList<QString> getInputs() const;
    void setInputs(const QList<QString> &inputs);

    QList<QString> getSigs() const;
    void setSigs(const QList<QString> &sigs);

    qint32 getLength() const;
    void setLength(const qint32 &length);

    QString getTxid() const;
    void setTxid(const QString &txid);

    qint32 getType() const;
    void setType(const qint32 &type);

    qint32 getTimestamp() const;
    void setTimestamp(const qint32 &timestamp);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QList<OAI_api_v1_explorer_address_outputs> outputs;
    bool m_outputs_isSet;
    bool m_outputs_isValid;
    QString inner_hash;
    bool m_inner_hash_isSet;
    bool m_inner_hash_isValid;
    QList<QString> inputs;
    bool m_inputs_isSet;
    bool m_inputs_isValid;
    QList<QString> sigs;
    bool m_sigs_isSet;
    bool m_sigs_isValid;
    qint32 length;
    bool m_length_isSet;
    bool m_length_isValid;
    QString txid;
    bool m_txid_isSet;
    bool m_txid_isValid;
    qint32 type;
    bool m_type_isSet;
    bool m_type_isValid;
    qint32 timestamp;
    bool m_timestamp_isSet;
    bool m_timestamp_isValid;
};

}

#endif // OAI_api_v1_pendingTxs_transaction_H
