/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_wallet_transaction_hours_selection.h
 *
 * 
 */

#ifndef OAI_api_v1_wallet_transaction_hours_selection_H
#define OAI_api_v1_wallet_transaction_hours_selection_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_wallet_transaction_hours_selection: public OAIObject {
public:
    OAI_api_v1_wallet_transaction_hours_selection();
    OAI_api_v1_wallet_transaction_hours_selection(QString json);
    ~OAI_api_v1_wallet_transaction_hours_selection() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getMode() const;
    void setMode(const QString &mode);

    QString getShareFactor() const;
    void setShareFactor(const QString &share_factor);

    QString getType() const;
    void setType(const QString &type);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString mode;
    bool m_mode_isSet;
    bool m_mode_isValid;
    QString share_factor;
    bool m_share_factor_isSet;
    bool m_share_factor_isValid;
    QString type;
    bool m_type_isSet;
    bool m_type_isValid;
};

}

#endif // OAI_api_v1_wallet_transaction_hours_selection_H
