/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAI_api_v1_explorer_address_status.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAI_api_v1_explorer_address_status::OAI_api_v1_explorer_address_status(QString json) {
    this->init();
    this->fromJson(json);
}

OAI_api_v1_explorer_address_status::OAI_api_v1_explorer_address_status() {
    this->init();
}

OAI_api_v1_explorer_address_status::~OAI_api_v1_explorer_address_status() {

}

void
OAI_api_v1_explorer_address_status::init() {
    m_unconfirmed_isSet = false;
    m_unconfirmed_isValid = false;
    m_block_seq_isSet = false;
    m_block_seq_isValid = false;
    m_label_isSet = false;
    m_label_isValid = false;
    m_confirmed_isSet = false;
    m_confirmed_isValid = false;
}

void
OAI_api_v1_explorer_address_status::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAI_api_v1_explorer_address_status::fromJsonObject(QJsonObject json) {
    m_unconfirmed_isValid = ::skyqt::fromJsonValue(unconfirmed, json[QString("unconfirmed")]);
    
    m_block_seq_isValid = ::skyqt::fromJsonValue(block_seq, json[QString("block_seq")]);
    
    m_label_isValid = ::skyqt::fromJsonValue(label, json[QString("label")]);
    
    m_confirmed_isValid = ::skyqt::fromJsonValue(confirmed, json[QString("confirmed")]);
    
}

QString
OAI_api_v1_explorer_address_status::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAI_api_v1_explorer_address_status::asJsonObject() const {
    QJsonObject obj;
	if(m_unconfirmed_isSet){
        obj.insert(QString("unconfirmed"), ::skyqt::toJsonValue(unconfirmed));
    }
	if(m_block_seq_isSet){
        obj.insert(QString("block_seq"), ::skyqt::toJsonValue(block_seq));
    }
	if(m_label_isSet){
        obj.insert(QString("label"), ::skyqt::toJsonValue(label));
    }
	if(m_confirmed_isSet){
        obj.insert(QString("confirmed"), ::skyqt::toJsonValue(confirmed));
    }
    return obj;
}

bool
OAI_api_v1_explorer_address_status::isUnconfirmed() const {
    return unconfirmed;
}
void
OAI_api_v1_explorer_address_status::setUnconfirmed(const bool &unconfirmed) {
    this->unconfirmed = unconfirmed;
    this->m_unconfirmed_isSet = true;
}

qint64
OAI_api_v1_explorer_address_status::getBlockSeq() const {
    return block_seq;
}
void
OAI_api_v1_explorer_address_status::setBlockSeq(const qint64 &block_seq) {
    this->block_seq = block_seq;
    this->m_block_seq_isSet = true;
}

qint64
OAI_api_v1_explorer_address_status::getLabel() const {
    return label;
}
void
OAI_api_v1_explorer_address_status::setLabel(const qint64 &label) {
    this->label = label;
    this->m_label_isSet = true;
}

bool
OAI_api_v1_explorer_address_status::isConfirmed() const {
    return confirmed;
}
void
OAI_api_v1_explorer_address_status::setConfirmed(const bool &confirmed) {
    this->confirmed = confirmed;
    this->m_confirmed_isSet = true;
}

bool
OAI_api_v1_explorer_address_status::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_unconfirmed_isSet){ isObjectUpdated = true; break;}
    
        if(m_block_seq_isSet){ isObjectUpdated = true; break;}
    
        if(m_label_isSet){ isObjectUpdated = true; break;}
    
        if(m_confirmed_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAI_api_v1_explorer_address_status::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

