/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_wallets_meta.h
 *
 * 
 */

#ifndef OAI_api_v1_wallets_meta_H
#define OAI_api_v1_wallets_meta_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_wallets_meta: public OAIObject {
public:
    OAI_api_v1_wallets_meta();
    OAI_api_v1_wallets_meta(QString json);
    ~OAI_api_v1_wallets_meta() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFilename() const;
    void setFilename(const QString &filename);

    bool isEncrypted() const;
    void setEncrypted(const bool &encrypted);

    QString getCryptoType() const;
    void setCryptoType(const QString &crypto_type);

    QString getLabel() const;
    void setLabel(const QString &label);

    QString getType() const;
    void setType(const QString &type);

    QString getVersion() const;
    void setVersion(const QString &version);

    QString getCoin() const;
    void setCoin(const QString &coin);

    qint32 getTimestamp() const;
    void setTimestamp(const qint32 &timestamp);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString filename;
    bool m_filename_isSet;
    bool m_filename_isValid;
    bool encrypted;
    bool m_encrypted_isSet;
    bool m_encrypted_isValid;
    QString crypto_type;
    bool m_crypto_type_isSet;
    bool m_crypto_type_isValid;
    QString label;
    bool m_label_isSet;
    bool m_label_isValid;
    QString type;
    bool m_type_isSet;
    bool m_type_isValid;
    QString version;
    bool m_version_isSet;
    bool m_version_isValid;
    QString coin;
    bool m_coin_isSet;
    bool m_coin_isValid;
    qint32 timestamp;
    bool m_timestamp_isSet;
    bool m_timestamp_isValid;
};

}

#endif // OAI_api_v1_wallets_meta_H
