/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAI_api_v1_wallet_transaction_to.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAI_api_v1_wallet_transaction_to::OAI_api_v1_wallet_transaction_to(QString json) {
    this->init();
    this->fromJson(json);
}

OAI_api_v1_wallet_transaction_to::OAI_api_v1_wallet_transaction_to() {
    this->init();
}

OAI_api_v1_wallet_transaction_to::~OAI_api_v1_wallet_transaction_to() {

}

void
OAI_api_v1_wallet_transaction_to::init() {
    m_hours_isSet = false;
    m_hours_isValid = false;
    m_address_isSet = false;
    m_address_isValid = false;
    m_coins_isSet = false;
    m_coins_isValid = false;
}

void
OAI_api_v1_wallet_transaction_to::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAI_api_v1_wallet_transaction_to::fromJsonObject(QJsonObject json) {
    m_hours_isValid = ::skyqt::fromJsonValue(hours, json[QString("hours")]);
    
    m_address_isValid = ::skyqt::fromJsonValue(address, json[QString("address")]);
    
    m_coins_isValid = ::skyqt::fromJsonValue(coins, json[QString("coins")]);
    
}

QString
OAI_api_v1_wallet_transaction_to::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAI_api_v1_wallet_transaction_to::asJsonObject() const {
    QJsonObject obj;
	if(m_hours_isSet){
        obj.insert(QString("hours"), ::skyqt::toJsonValue(hours));
    }
	if(m_address_isSet){
        obj.insert(QString("address"), ::skyqt::toJsonValue(address));
    }
	if(m_coins_isSet){
        obj.insert(QString("coins"), ::skyqt::toJsonValue(coins));
    }
    return obj;
}

qint64
OAI_api_v1_wallet_transaction_to::getHours() const {
    return hours;
}
void
OAI_api_v1_wallet_transaction_to::setHours(const qint64 &hours) {
    this->hours = hours;
    this->m_hours_isSet = true;
}

QString
OAI_api_v1_wallet_transaction_to::getAddress() const {
    return address;
}
void
OAI_api_v1_wallet_transaction_to::setAddress(const QString &address) {
    this->address = address;
    this->m_address_isSet = true;
}

qint64
OAI_api_v1_wallet_transaction_to::getCoins() const {
    return coins;
}
void
OAI_api_v1_wallet_transaction_to::setCoins(const qint64 &coins) {
    this->coins = coins;
    this->m_coins_isSet = true;
}

bool
OAI_api_v1_wallet_transaction_to::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_hours_isSet){ isObjectUpdated = true; break;}
    
        if(m_address_isSet){ isObjectUpdated = true; break;}
    
        if(m_coins_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAI_api_v1_wallet_transaction_to::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

