/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_api_v1_explorer_address_outputs.h
 *
 * 
 */

#ifndef OAI_api_v1_explorer_address_outputs_H
#define OAI_api_v1_explorer_address_outputs_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAI_api_v1_explorer_address_outputs: public OAIObject {
public:
    OAI_api_v1_explorer_address_outputs();
    OAI_api_v1_explorer_address_outputs(QString json);
    ~OAI_api_v1_explorer_address_outputs() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getHours() const;
    void setHours(const qint64 &hours);

    QString getDst() const;
    void setDst(const QString &dst);

    QString getCoins() const;
    void setCoins(const QString &coins);

    QString getUxid() const;
    void setUxid(const QString &uxid);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    qint64 hours;
    bool m_hours_isSet;
    bool m_hours_isValid;
    QString dst;
    bool m_dst_isSet;
    bool m_dst_isValid;
    QString coins;
    bool m_coins_isSet;
    bool m_coins_isValid;
    QString uxid;
    bool m_uxid_isSet;
    bool m_uxid_isValid;
};

}

#endif // OAI_api_v1_explorer_address_outputs_H
