/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200.h
 *
 * 
 */

#ifndef OAIInline_response_200_H
#define OAIInline_response_200_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200: public OAIObject {
public:
    OAIInline_response_200();
    OAIInline_response_200(QString json);
    ~OAIInline_response_200() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getHours() const;
    void setHours(const qint64 &hours);

    qint32 getCoins() const;
    void setCoins(const qint32 &coins);

    QString getUxid() const;
    void setUxid(const QString &uxid);

    QString getOwnerAddress() const;
    void setOwnerAddress(const QString &owner_address);

    qint32 getSpentBlockSeq() const;
    void setSpentBlockSeq(const qint32 &spent_block_seq);

    QString getSpentTx() const;
    void setSpentTx(const QString &spent_tx);

    qint64 getTime() const;
    void setTime(const qint64 &time);

    qint64 getSrcBlockSeq() const;
    void setSrcBlockSeq(const qint64 &src_block_seq);

    QString getSrcTx() const;
    void setSrcTx(const QString &src_tx);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    qint64 hours;
    bool m_hours_isSet;
    bool m_hours_isValid;
    qint32 coins;
    bool m_coins_isSet;
    bool m_coins_isValid;
    QString uxid;
    bool m_uxid_isSet;
    bool m_uxid_isValid;
    QString owner_address;
    bool m_owner_address_isSet;
    bool m_owner_address_isValid;
    qint32 spent_block_seq;
    bool m_spent_block_seq_isSet;
    bool m_spent_block_seq_isValid;
    QString spent_tx;
    bool m_spent_tx_isSet;
    bool m_spent_tx_isValid;
    qint64 time;
    bool m_time_isSet;
    bool m_time_isValid;
    qint64 src_block_seq;
    bool m_src_block_seq_isSet;
    bool m_src_block_seq_isValid;
    QString src_tx;
    bool m_src_tx_isSet;
    bool m_src_tx_isValid;
};

}

#endif // OAIInline_response_200_H
