/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_200_7_data.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAIInline_response_200_7_data::OAIInline_response_200_7_data(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_200_7_data::OAIInline_response_200_7_data() {
    this->init();
}

OAIInline_response_200_7_data::~OAIInline_response_200_7_data() {

}

void
OAIInline_response_200_7_data::init() {
    m_version_isSet = false;
    m_version_isValid = false;
}

void
OAIInline_response_200_7_data::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_200_7_data::fromJsonObject(QJsonObject json) {
    m_version_isValid = ::skyqt::fromJsonValue(version, json[QString("version")]);
    
}

QString
OAIInline_response_200_7_data::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_200_7_data::asJsonObject() const {
    QJsonObject obj;
	if(m_version_isSet){
        obj.insert(QString("version"), ::skyqt::toJsonValue(version));
    }
    return obj;
}

qint64
OAIInline_response_200_7_data::getVersion() const {
    return version;
}
void
OAIInline_response_200_7_data::setVersion(const qint64 &version) {
    this->version = version;
    this->m_version_isSet = true;
}

bool
OAIInline_response_200_7_data::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_version_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_200_7_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

