/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_4.h
 *
 * 
 */

#ifndef OAIInline_response_200_4_H
#define OAIInline_response_200_4_H

#include <QJsonObject>


#include "OAI_api_v1_pendingTxs_transaction.h"
#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_4: public OAIObject {
public:
    OAIInline_response_200_4();
    OAIInline_response_200_4(QString json);
    ~OAIInline_response_200_4() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getAnnounced() const;
    void setAnnounced(const QString &announced);

    bool isIsValid() const;
    void setIsValid(const bool &is_valid);

    QString getChecked() const;
    void setChecked(const QString &checked);

    QString getReceived() const;
    void setReceived(const QString &received);

    OAI_api_v1_pendingTxs_transaction getTransaction() const;
    void setTransaction(const OAI_api_v1_pendingTxs_transaction &transaction);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString announced;
    bool m_announced_isSet;
    bool m_announced_isValid;
    bool is_valid;
    bool m_is_valid_isSet;
    bool m_is_valid_isValid;
    QString checked;
    bool m_checked_isSet;
    bool m_checked_isValid;
    QString received;
    bool m_received_isSet;
    bool m_received_isValid;
    OAI_api_v1_pendingTxs_transaction transaction;
    bool m_transaction_isSet;
    bool m_transaction_isValid;
};

}

#endif // OAIInline_response_200_4_H
