/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_6.h
 *
 * 
 */

#ifndef OAIInline_response_200_6_H
#define OAIInline_response_200_6_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_6: public OAIObject {
public:
    OAIInline_response_200_6();
    OAIInline_response_200_6(QString json);
    ~OAIInline_response_200_6() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getAddress() const;
    void setAddress(const QString &address);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString address;
    bool m_address_isSet;
    bool m_address_isValid;
};

}

#endif // OAIInline_response_200_6_H
