/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_object.h
 *
 * 
 */

#ifndef OAIInline_object_H
#define OAIInline_object_H

#include <QJsonObject>


#include "OAI_api_v1_wallet_transaction_hours_selection.h"
#include "OAI_api_v1_wallet_transaction_to.h"
#include "OAI_api_v1_wallet_transaction_wallet.h"
#include <QList>
#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_object: public OAIObject {
public:
    OAIInline_object();
    OAIInline_object(QString json);
    ~OAIInline_object() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getChangeAddress() const;
    void setChangeAddress(const QString &change_address);

    OAI_api_v1_wallet_transaction_hours_selection getHoursSelection() const;
    void setHoursSelection(const OAI_api_v1_wallet_transaction_hours_selection &hours_selection);

    bool isIgnoreUnconfirmed() const;
    void setIgnoreUnconfirmed(const bool &ignore_unconfirmed);

    QList<OAI_api_v1_wallet_transaction_to> getTo() const;
    void setTo(const QList<OAI_api_v1_wallet_transaction_to> &to);

    OAI_api_v1_wallet_transaction_wallet getWallet() const;
    void setWallet(const OAI_api_v1_wallet_transaction_wallet &wallet);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QString change_address;
    bool m_change_address_isSet;
    bool m_change_address_isValid;
    OAI_api_v1_wallet_transaction_hours_selection hours_selection;
    bool m_hours_selection_isSet;
    bool m_hours_selection_isValid;
    bool ignore_unconfirmed;
    bool m_ignore_unconfirmed_isSet;
    bool m_ignore_unconfirmed_isValid;
    QList<OAI_api_v1_wallet_transaction_to> to;
    bool m_to_isSet;
    bool m_to_isValid;
    OAI_api_v1_wallet_transaction_wallet wallet;
    bool m_wallet_isSet;
    bool m_wallet_isValid;
};

}

#endif // OAIInline_object_H
