/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_2.h
 *
 * 
 */

#ifndef OAIInline_response_200_2_H
#define OAIInline_response_200_2_H

#include <QJsonObject>


#include "OAI_api_v1_explorer_address_inputs.h"
#include "OAI_api_v1_explorer_address_outputs.h"
#include "OAI_api_v1_explorer_address_status.h"
#include <QList>
#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_2: public OAIObject {
public:
    OAIInline_response_200_2();
    OAIInline_response_200_2(QString json);
    ~OAIInline_response_200_2() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAI_api_v1_explorer_address_outputs> getOutputs() const;
    void setOutputs(const QList<OAI_api_v1_explorer_address_outputs> &outputs);

    QString getInnerHash() const;
    void setInnerHash(const QString &inner_hash);

    QList<OAI_api_v1_explorer_address_inputs> getInputs() const;
    void setInputs(const QList<OAI_api_v1_explorer_address_inputs> &inputs);

    qint32 getFee() const;
    void setFee(const qint32 &fee);

    QList<QString> getSigs() const;
    void setSigs(const QList<QString> &sigs);

    qint64 getLength() const;
    void setLength(const qint64 &length);

    QString getTxid() const;
    void setTxid(const QString &txid);

    qint32 getType() const;
    void setType(const qint32 &type);

    OAI_api_v1_explorer_address_status getStatus() const;
    void setStatus(const OAI_api_v1_explorer_address_status &status);

    qint32 getTimestamp() const;
    void setTimestamp(const qint32 &timestamp);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    QList<OAI_api_v1_explorer_address_outputs> outputs;
    bool m_outputs_isSet;
    bool m_outputs_isValid;
    QString inner_hash;
    bool m_inner_hash_isSet;
    bool m_inner_hash_isValid;
    QList<OAI_api_v1_explorer_address_inputs> inputs;
    bool m_inputs_isSet;
    bool m_inputs_isValid;
    qint32 fee;
    bool m_fee_isSet;
    bool m_fee_isValid;
    QList<QString> sigs;
    bool m_sigs_isSet;
    bool m_sigs_isValid;
    qint64 length;
    bool m_length_isSet;
    bool m_length_isValid;
    QString txid;
    bool m_txid_isSet;
    bool m_txid_isValid;
    qint32 type;
    bool m_type_isSet;
    bool m_type_isValid;
    OAI_api_v1_explorer_address_status status;
    bool m_status_isSet;
    bool m_status_isValid;
    qint32 timestamp;
    bool m_timestamp_isSet;
    bool m_timestamp_isValid;
};

}

#endif // OAIInline_response_200_2_H
