/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_default.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAIInline_response_default::OAIInline_response_default(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_default::OAIInline_response_default() {
    this->init();
}

OAIInline_response_default::~OAIInline_response_default() {

}

void
OAIInline_response_default::init() {
    m_code_isSet = false;
    m_code_isValid = false;
    m_message_isSet = false;
    m_message_isValid = false;
}

void
OAIInline_response_default::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_default::fromJsonObject(QJsonObject json) {
    m_code_isValid = ::skyqt::fromJsonValue(code, json[QString("code")]);
    
    m_message_isValid = ::skyqt::fromJsonValue(message, json[QString("message")]);
    
}

QString
OAIInline_response_default::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_default::asJsonObject() const {
    QJsonObject obj;
	if(m_code_isSet){
        obj.insert(QString("code"), ::skyqt::toJsonValue(code));
    }
	if(m_message_isSet){
        obj.insert(QString("message"), ::skyqt::toJsonValue(message));
    }
    return obj;
}

qint32
OAIInline_response_default::getCode() const {
    return code;
}
void
OAIInline_response_default::setCode(const qint32 &code) {
    this->code = code;
    this->m_code_isSet = true;
}

QString
OAIInline_response_default::getMessage() const {
    return message;
}
void
OAIInline_response_default::setMessage(const QString &message) {
    this->message = message;
    this->m_message_isSet = true;
}

bool
OAIInline_response_default::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_code_isSet){ isObjectUpdated = true; break;}
    
        if(m_message_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_default::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

