/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_200_5.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAIInline_response_200_5::OAIInline_response_200_5(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_200_5::OAIInline_response_200_5() {
    this->init();
}

OAIInline_response_200_5::~OAIInline_response_200_5() {

}

void
OAIInline_response_200_5::init() {
    m_entries_isSet = false;
    m_entries_isValid = false;
    m_meta_isSet = false;
    m_meta_isValid = false;
}

void
OAIInline_response_200_5::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_200_5::fromJsonObject(QJsonObject json) {
    
    m_entries_isValid = ::skyqt::fromJsonValue(entries, json[QString("entries")]);
    m_meta_isValid = ::skyqt::fromJsonValue(meta, json[QString("meta")]);
    
}

QString
OAIInline_response_200_5::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_200_5::asJsonObject() const {
    QJsonObject obj;
	
    if(entries.size() > 0){
        obj.insert(QString("entries"), ::skyqt::toJsonValue(entries));
    } 
	if(meta.isSet()){
        obj.insert(QString("meta"), ::skyqt::toJsonValue(meta));
    }
    return obj;
}

QList<OAI_api_v1_wallets_entries>
OAIInline_response_200_5::getEntries() const {
    return entries;
}
void
OAIInline_response_200_5::setEntries(const QList<OAI_api_v1_wallets_entries> &entries) {
    this->entries = entries;
    this->m_entries_isSet = true;
}

OAI_api_v1_wallets_meta
OAIInline_response_200_5::getMeta() const {
    return meta;
}
void
OAIInline_response_200_5::setMeta(const OAI_api_v1_wallets_meta &meta) {
    this->meta = meta;
    this->m_meta_isSet = true;
}

bool
OAIInline_response_200_5::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(entries.size() > 0){ isObjectUpdated = true; break;}
    
        if(meta.isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_200_5::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

