/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_200_6.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAIInline_response_200_6::OAIInline_response_200_6(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_200_6::OAIInline_response_200_6() {
    this->init();
}

OAIInline_response_200_6::~OAIInline_response_200_6() {

}

void
OAIInline_response_200_6::init() {
    m_address_isSet = false;
    m_address_isValid = false;
}

void
OAIInline_response_200_6::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_200_6::fromJsonObject(QJsonObject json) {
    m_address_isValid = ::skyqt::fromJsonValue(address, json[QString("address")]);
    
}

QString
OAIInline_response_200_6::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_200_6::asJsonObject() const {
    QJsonObject obj;
	if(m_address_isSet){
        obj.insert(QString("address"), ::skyqt::toJsonValue(address));
    }
    return obj;
}

QString
OAIInline_response_200_6::getAddress() const {
    return address;
}
void
OAIInline_response_200_6::setAddress(const QString &address) {
    this->address = address;
    this->m_address_isSet = true;
}

bool
OAIInline_response_200_6::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_address_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_200_6::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

