/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_7.h
 *
 * 
 */

#ifndef OAIInline_response_200_7_H
#define OAIInline_response_200_7_H

#include <QJsonObject>


#include "OAIInline_response_200_7_data.h"
#include "OAIObject.h"

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_7: public OAIObject {
public:
    OAIInline_response_200_7();
    OAIInline_response_200_7(QString json);
    ~OAIInline_response_200_7() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIInline_response_200_7_data getData() const;
    void setData(const OAIInline_response_200_7_data &data);

    OAIObject getError() const;
    void setError(const OAIObject &error);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    OAIInline_response_200_7_data data;
    bool m_data_isSet;
    bool m_data_isValid;
    OAIObject error;
    bool m_error_isSet;
    bool m_error_isValid;
};

}

#endif // OAIInline_response_200_7_H
