/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_7_data.h
 *
 * 
 */

#ifndef OAIInline_response_200_7_data_H
#define OAIInline_response_200_7_data_H

#include <QJsonObject>



#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_7_data: public OAIObject {
public:
    OAIInline_response_200_7_data();
    OAIInline_response_200_7_data(QString json);
    ~OAIInline_response_200_7_data() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getVersion() const;
    void setVersion(const qint64 &version);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    qint64 version;
    bool m_version_isSet;
    bool m_version_isValid;
};

}

#endif // OAIInline_response_200_7_data_H
