/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_3_unconfirmed_verify_transaction.h
 *
 * Represent unconfirmed transactions
 */

#ifndef OAIInline_response_200_3_unconfirmed_verify_transaction_H
#define OAIInline_response_200_3_unconfirmed_verify_transaction_H

#include <QJsonObject>



#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_200_3_unconfirmed_verify_transaction: public OAIObject {
public:
    OAIInline_response_200_3_unconfirmed_verify_transaction();
    OAIInline_response_200_3_unconfirmed_verify_transaction(QString json);
    ~OAIInline_response_200_3_unconfirmed_verify_transaction() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getBurnFactor() const;
    void setBurnFactor(const qint32 &burn_factor);

    qint32 getMaxTransactionSize() const;
    void setMaxTransactionSize(const qint32 &max_transaction_size);

    qint32 getMaxDecimals() const;
    void setMaxDecimals(const qint32 &max_decimals);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    qint32 burn_factor;
    bool m_burn_factor_isSet;
    bool m_burn_factor_isValid;
    qint32 max_transaction_size;
    bool m_max_transaction_size_isSet;
    bool m_max_transaction_size_isValid;
    qint32 max_decimals;
    bool m_max_decimals_isSet;
    bool m_max_decimals_isValid;
};

}

#endif // OAIInline_response_200_3_unconfirmed_verify_transaction_H
