/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_default.h
 *
 * 
 */

#ifndef OAIInline_response_default_H
#define OAIInline_response_default_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace skyqt {

class OAIInline_response_default: public OAIObject {
public:
    OAIInline_response_default();
    OAIInline_response_default(QString json);
    ~OAIInline_response_default() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getCode() const;
    void setCode(const qint32 &code);

    QString getMessage() const;
    void setMessage(const QString &message);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    qint32 code;
    bool m_code_isSet;
    bool m_code_isValid;
    QString message;
    bool m_message_isSet;
    bool m_message_isValid;
};

}

#endif // OAIInline_response_default_H
