/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_200_7.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace skyqt {

OAIInline_response_200_7::OAIInline_response_200_7(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_200_7::OAIInline_response_200_7() {
    this->init();
}

OAIInline_response_200_7::~OAIInline_response_200_7() {

}

void
OAIInline_response_200_7::init() {
    m_data_isSet = false;
    m_data_isValid = false;
    m_error_isSet = false;
    m_error_isValid = false;
}

void
OAIInline_response_200_7::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_200_7::fromJsonObject(QJsonObject json) {
    m_data_isValid = ::skyqt::fromJsonValue(data, json[QString("data")]);
    
    m_error_isValid = ::skyqt::fromJsonValue(error, json[QString("error")]);
    
}

QString
OAIInline_response_200_7::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_200_7::asJsonObject() const {
    QJsonObject obj;
	if(data.isSet()){
        obj.insert(QString("data"), ::skyqt::toJsonValue(data));
    }
	if(m_error_isSet){
        obj.insert(QString("error"), ::skyqt::toJsonValue(error));
    }
    return obj;
}

OAIInline_response_200_7_data
OAIInline_response_200_7::getData() const {
    return data;
}
void
OAIInline_response_200_7::setData(const OAIInline_response_200_7_data &data) {
    this->data = data;
    this->m_data_isSet = true;
}

OAIObject
OAIInline_response_200_7::getError() const {
    return error;
}
void
OAIInline_response_200_7::setError(const OAIObject &error) {
    this->error = error;
    this->m_error_isSet = true;
}

bool
OAIInline_response_200_7::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(data.isSet()){ isObjectUpdated = true; break;}
    
        if(m_error_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_200_7::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

